name: react
on:
  push:
    branches: [ main ]
jobs:
  docker-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Not on Monday or Wednesday       
        run: env
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Login Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      #   id: buildx


      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v2
      #   id: docker_build
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: "${{ secrets.DOCKERHUB_USERNAME }}/flask-helloworld:$GITHUB_BASE_REF"
      #     # cache-from: type=local,src=/tmp/.buildx-cache
      #     # cache-to: type=local,dest=/tmp/.buildx-cache

      # - name: Verify
      #   run: echo ${{ steps.docker_build.outputs.digest }}

      